trigger:
- main

pool: 'Default'

steps:
- script: |
    wget -c --header "Cookie: oraclelicense=accept-securebackup-cookie" -O jdk-21_linux-x64_bin.tar.gz https://download.oracle.com/java/21/latest/jdk-21_linux-x64_bin.tar.gz
    tar -xzf jdk-21_linux-x64_bin.tar.gz -C $(Agent.ToolsDirectory)/jdk21
  displayName: 'Download and extract JDK 21'

- task: JavaToolInstaller@0
  displayName: 'Use Java 21'
  inputs:
    versionSpec: 21
    jdkArchitectureOption: x64
    jdkSourceOption: LocalDirectory
    jdkFile: '$(Agent.ToolsDirectory)/jdk21'
    jdkDestinationDirectory: '$(Agent.ToolsDirectory)/jdk21'

- task: Gradle@3
  inputs:
    workingDirectory: ''
    gradleWrapperFile: 'gradlew'
    gradleOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml'
    tasks: 'build'
