trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    mkdir -p $(Agent.ToolsDirectory)/jdk21
    wget -c --header "Cookie: oraclelicense=accept-securebackup-cookie" -O jdk-21_linux-x64_bin.tar.gz https://download.oracle.com/java/21/latest/jdk-21_linux-x64_bin.tar.gz
    tar -xzf jdk-21_linux-x64_bin.tar.gz -C $(Agent.ToolsDirectory)/jdk21 --strip-components=1
    echo "##vso[task.setvariable variable=JAVA_HOME]$(Agent.ToolsDirectory)/jdk21"
    echo "##vso[task.prependpath]$(Agent.ToolsDirectory)/jdk21/bin"
  displayName: 'Download and extract JDK 21'

- script: |
    mvn -version
  displayName: 'Verify Maven Installation'

- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean install'
    options: '-Xmx3072m'
    publishJUnitResults: true
    testResultsFiles: '**/target/surefire-reports/TEST-*.xml'
  displayName: 'Run Maven Build'
